name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: 'Build and Restart'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/leadharmony/
            echo "${{ secrets.BE_ENV_FILE }}" > .env
            git pull origin main
            npm install --force
            npm run migrate:deploy
            npm run build
            pm2 restart 0
            pm2 restart 1
            pm2 save
